### ISSUE TITLE
update readme file with step by step process to migrate

### ISSUE THREAD

**Issue by Hari-Bonda** [serkanalgur/flarum-to-wordpress#5]
thanks a lot for this migration script, could you update the readme file with step by step process to migrate

do we need to put sql/mariaDB logins in migration script files?

**Comment by serkanalgur** [comment]
Hello @Hari-Bonda,

Plugin not completed yet, but I will create a form are within the plugin management page. I am currently working on some other project but I will finish this plugin asap.
